(shmif) add missing header after 8578606be492
src/shmif/arcan_shmif_server.c:381:4: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  381 |                         kill(*pid, SIGKILL);
      |                         ^
src/shmif/arcan_shmif_server.c:381:15: error: use of undeclared identifier 'SIGKILL'
  381 |                         kill(*pid, SIGKILL);
      |                                    ^
src/shmif/arcan_shmif_server.c:420:4: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  420 |                         kill(cl->pid, SIGKILL);
      |                         ^
src/shmif/arcan_shmif_server.c:420:18: error: use of undeclared identifier 'SIGKILL'
  420 |                         kill(cl->pid, SIGKILL);
      |                                       ^