(CI) unbreak FreeBSD build (#286)
* (shmif) add missing header after 8578606be492

src/shmif/arcan_shmif_server.c:381:4: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  381 |                         kill(*pid, SIGKILL);
      |                         ^
src/shmif/arcan_shmif_server.c:381:15: error: use of undeclared identifier 'SIGKILL'
  381 |                         kill(*pid, SIGKILL);
      |                                    ^
src/shmif/arcan_shmif_server.c:420:4: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  420 |                         kill(cl->pid, SIGKILL);
      |                         ^
src/shmif/arcan_shmif_server.c:420:18: error: use of undeclared identifier 'SIGKILL'
  420 |                         kill(cl->pid, SIGKILL);
      |                                       ^

* CI: skip install step to reduce noise

* CI: disable copyback to avoid spurious failures

See also https://github.com/mpv-player/mpv/commit/e7902eb83dc6

FossilOrigin-Name: 4fd4911b0e6eacbbb824ea412658f10fd4af093c5e14a40914b08cd58e65217a