(build) add missing include after c80cd084921c (#254)
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /man1/aclip.1
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/man/man1/aclip.1.gz

FossilOrigin-Name: 824aab08d5284df52da8329ef3b42b1054fa0b1948110f12cec6b2ebcf842a58