(build) use correct macro to unhide getline()
`_WITH_DPRINTF_` doesn't exist while `_WITH_DPRINTF` did on FreeBSD < 12
but Arcan never used `dprintf`. And `getline` on FreeBSD < 12 is hidden
behind a different macro.

src/frameserver/util/anet_keystore_naive.c:231:10: warning: implicit declaration of function 'getline' is invalid in C99 [-Wimplicit-function-declaration]
                while (getline(&inbuf, &len, fpek) != -1){
                       ^
src/frameserver/util/anet_keystore_naive.c:427:15: warning: implicit declaration of function 'getline' is invalid in C99 [-Wimplicit-function-declaration]
        while ((nr = getline(&inbuf, &len, fpek)) != -1){
                     ^

FossilOrigin-Name: dd7b76e00b89bf5360684647e546b52f1946a4684f65f2bc8d06a02f260a69b9