(build/vrbridge) find bundled hidapi headers
FAILED: CMakeFiles/arcan_vr.dir/openhmd.c.o
/usr/bin/cc -DGNU_SOURCE -DLIBUSB_BSD -DPOSIX_C_SOURCE -D__UNIX -I/usr/local/include/arcan/shmif -Isrc/tools/vrbridge/../../../src/engine -Isrc/tools/vrbridge/OpenHMD -Wall -Wno-unused-const-variable -Wno-unused-function -pthread -MD -MT CMakeFiles/arcan_vr.dir/openhmd.c.o -MF CMakeFiles/arcan_vr.dir/openhmd.c.o.d -o CMakeFiles/arcan_vr.dir/openhmd.c.o -c src/tools/vrbridge/openhmd.c
src/tools/vrbridge/openhmd.c:7:10: fatal error: 'hidapi/hidapi.h' file not found
 #include <hidapi/hidapi.h>
          ^~~~~~~~~~~~~~~~~
1 error generated.