(build) install manpage on DragonFly similar to FreeBSD
Allows DragonFly to consume FreeBSD package recipe as is.

$ make check-plist -C sysutils/acfgfs
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/man/man1/arcan_cfgfs.1.gz
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: man/man1/arcan_cfgfs.1.gz
===> Error: Plist issues found.
*** Error code 1